## 와인 데이터 분류
- 화이트 와인, 레드 와인으로 분류

In [3]:
import pandas as pd

wine = pd.read_csv('https://bit.ly/wine_csv_data')
wine.head()

   alcohol  sugar    pH  class
0      9.4    1.9  3.51    0.0
1      9.8    2.6  3.20    0.0
2      9.8    2.3  3.26    0.0
3      9.8    1.9  3.16    0.0
4      9.4    1.9  3.51    0.0

In [5]:
wine['class'].value_counts()

1.0    4898
0.0    1599
Name: class, dtype: int64

In [6]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   alcohol  6497 non-null   float64
 1   sugar    6497 non-null   float64
 2   pH       6497 non-null   float64
 3   class    6497 non-null   float64
dtypes: float64(4)
memory usage: 203.2 KB

## 데이터 셋 분리

In [24]:
# 독립변수
data = wine[['alcohol', 'sugar', 'pH']].to_numpy()

# 종속변수
target = wine['class'].to_numpy()

array([[ 9.4 ,  1.9 ,  3.51],
       [ 9.8 ,  2.6 ,  3.2 ],
       [ 9.8 ,  2.3 ,  3.26],
       ...,
       [ 9.4 ,  1.2 ,  2.99],
       [12.8 ,  1.1 ,  3.34],
       [11.8 ,  0.8 ,  3.26]])

In [11]:
from sklearn.model_selection import train_test_split
                                                                                 # 실험 재현성
x_train, x_test, y_train, y_test = train_test_split(data, target, test_size = 0.2, random_state =  42)

x_train.shape, x_test.shape, y_train.shape, y_test.shape

((5197, 3), (1300, 3), (5197,), (1300,))

In [12]:
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size = 0.2, random_state =  42)

x_train.shape, x_val.shape, y_train.shape, y_val.shape

((4157, 3), (1040, 3), (4157,), (1040,))

## 모형 만들기

In [13]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state = 42)
dt.fit(x_train, y_train)

DecisionTreeClassifier(random_state=42)

In [15]:
dt.score(x_train, y_train)

0.9971133028626413

In [18]:
dt.score(x_val, y_val)

0.864423076923077

## 교차검증

In [21]:
from sklearn.model_selection import cross_validate

scores = cross_validate(dt, x_train, y_train)
print(scores)

{'fit_time': array([0.01112866, 0.00585461, 0.00592351, 0.00602365, 0.00616097]), 'score_time': array([0.0008657 , 0.00067306, 0.00061274, 0.00064063, 0.00088167]), 'test_score': array([0.84975962, 0.85456731, 0.85679904, 0.81588448, 0.84837545])}

In [22]:
import numpy as np

print(np.mean(scores['test_score']))

0.8450771776358419

## 구글 드라이브 연동

In [26]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## 데이터 불러오기

In [28]:
# /content/drive/MyDrive/Colab Notebooks/2023/human/titanic

import pandas as pd

DATA_PATH =  '/content/drive/MyDrive/Colab Notebooks/2023/human/titanic'
train_df = pd.read_csv(DATA_PATH + '/train.csv')
test_df = pd.read_csv(DATA_PATH + '/test.csv')

- 데이터를 확인

In [29]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

- 결측치의 비율 확인

In [33]:
# train_df.shape
(train_df.isnull().sum() / train_df.shape[0]).sort_values(ascending = False)

Cabin          0.771044
Age            0.198653
Embarked       0.002245
PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
dtype: float64

In [34]:
train_df.describe(include = 'all')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,B96 B98,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

## 데이터 시각화
- 각 칼럼별 ~ 종속변수
 - 박스플롯, 산점도, 히스토그램 등등 ,, 다양한 그래프를 그립니다.
- 탐색적 자료분석 (EDA : Exploratory Data Analysis)

## 모형 개발 코드 작성
- 파이프라인 구축
- pycaret 모형 만들때는, 내부적으로는 파이프라인 통해서 구현

In [45]:
from sklearn.pipeline import Pipeline

# NA, NULL.. 결측지 값에 특정 값을 추가하는 방법(가장 단순한)
from sklearn.impute import SimpleImputer

# 수치 데이터를 변환
# 최소와 최대가 0 ~ 1 사이
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder

# 
from sklearn.compose import ColumnTransformer

# 숫자로 된 칼럼
num_features = ['Age', 'Fare', 'SibSp', 'Parch']
# 문자로 된 칼럼
cat_features = ['Embarked', 'Sex', 'Pclass']
# 필요 없는 칼럼
rem_features = ['Name', 'Cabin', 'Ticket', 'PassengerId']

# 각 데이터 타입에 맞는 transformer 구성
# 수치 데이터 결측지 값 채우는 방법 : 평균 또는 중간값
# 중간값으로 넣기
num_transformer = Pipeline(steps = [
    ('imputer', SimpleImputer(strategy = 'median')),
    ('scaler', MinMaxScaler())
])

# 문자 데이터 결측지 값 채우는 방법 : 가장 빈도수가 많은 데이터를 추가
cat_transformer = Pipeline(steps = [
    ('imputer', SimpleImputer(strategy = 'most_frequent')),
    ('onehot', OneHotEncoder())
])

# # 데이터 전처리기 파이프라인 구성
# preprocessor = ColumnTransformer(
#     transformer = [
#         ('numeric_features', num_transformer, num_features),     # 수치 데이터 변환기
#         ('category_features', cat_transformer, cat_features),     # 문자 데이터 변환기
#         ('remove_features', 'drop', rem_features)               # 불필요한 컬럼 제거
#     ]
# )

# 데이터 전처리기 파이프라인 구성
preprocessor = ColumnTransformer(
    transformers = [
        ('numeric_features', num_transformer, num_features), # 수치 데이터 변환기  
        ('category_features', cat_transformer, cat_features), # 문자 데이터 변환기 
        ('remove_features', 'drop', rem_features)  # 불필요한 컬럼 제거
    ]
)

In [46]:
# 독립변수, 종속변수
target = train_df['Survived'].copy()
train_df = train_df.drop(['Survived'], axis = 1)

train_df.shape, target.shape

KeyError: ignored

In [47]:
# 로지스틱 회구분석 (-- 딥러닝 교육할 때 다시 배울 예정)
from sklearn.linear_model import LogisticRegression

# 모델 파이프라인 연결
model = Pipeline([
    ('preprocessor', preprocessor),
    ('clf', LogisticRegression(solver = 'liblinear'))
])

model.fit(train_df, target)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('numeric_features',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   MinMaxScaler())]),
                                                  ['Age', 'Fare', 'SibSp',
                                                   'Parch']),
                                                 ('category_features',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder())]),
                                                  ['Embarked', 'Sex',
                                                   'Pclass']),
                                                 ('remove_features', 'drop',
                                                  ['Name', 'Cabin', 'Ticket',
                                                   'PassengerId'])])),
                ('clf', LogisticRegression(solver='liblinear'))])

In [48]:
accuray_score = round(model.score(train_df, target) * 100, 2)
accuray_score

80.02

## 모형 예측 및 csv 파일 변환

In [50]:
y_pred = model.predict(test_df)
# y_pred

submission = pd.DataFrame({
    'PassengerId' : test_df['PassengerId'],
    'Survived' : y_pred
})


submission.to_csv(DATA_PATH + '/submission.csv', index = False)